name = "leanlevy"
version = "0.1.0"
defaultTargets = ["leanlevy"]

[[lean_lib]]
name = "LeanLevy"

[[lean_exe]]
name = "leanlevy"
root = "Main"

[[require]]
name = "mathlib4"
git = "https://github.com/leanprover-community/mathlib4"
